name: 'Terraform'

on: 
  workflow_dispatch:
  push:
    branches:
    - main


jobs:
  terraform-dev-plan:
    name: 'Terraform Plan - Dev'
    strategy:
      matrix: 
        test-env: ["dev", "prod"]

    runs-on: ubuntu-latest
    environment: ${{ matrix.test-env }}
    max-parallel: 1
    
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
      - name: Get IP
        id: get-aget-ip
        shell: bash
        run: |
          IP=$(curl "https://api.ipify.org")
          echo ${{ matrix.test-env }} $IP
          echo "agent_ip=$(echo $IP)" >> $GITHUB_OUTPUT
          

      - name: Output IP
        run: |
          echo "Whitelisted ${{ steps.get-aget-ip.outputs.agent_ip }} on storage account devopsintegrations"
